# Generated by Django 5.2.10 on 2026-01-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo precisará estar marcadopara a pagina ser exibida publicamente.'),
        ),
    ]
